# Generated by Django 3.2.4 on 2021-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
